//! Equivalence test: replay golden data captured from the REAL MicroPython
//! `kiln/pid.py` and assert the Rust port produces matching outputs.
//!
//! The fixture (`tests/fixtures/pid_golden.csv`) is generated by
//! `tools/gen_pid_golden.py`, which imports the production PID unchanged and
//! drives it through ramp / hold / step-down phases that exercise proportional,
//! integral, derivative, output saturation and anti-windup behaviour.
//!
//! Floats in the fixture are written with Python `repr()`, so they round-trip
//! exactly through `f64` parsing here; with identical op order the results match
//! far tighter than the tolerance below.

use kiln_core::Pid;
use std::path::PathBuf;

/// Absolute tolerance. f64 with identical arithmetic order agrees to within a
/// few ULP (~1e-9 at these magnitudes); 1e-6 is generous headroom.
const TOL: f64 = 1e-6;

struct Row {
    idx: usize,
    time_s: f64,
    setpoint: f64,
    measured: f64,
    output: f64,
    p_term: f64,
    i_term: f64,
    d_term: f64,
    integral_frozen: bool,
}

fn fixture_path() -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "tests", "fixtures", "pid_golden.csv"]
        .iter()
        .collect()
}

fn load_rows() -> Vec<Row> {
    let path = fixture_path();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read fixture {path:?}: {e}\nrun: python3 rust/kiln-core/tools/gen_pid_golden.py"));

    let mut rows = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if i == 0 || line.trim().is_empty() {
            continue; // header / blanks
        }
        let c: Vec<&str> = line.split(',').collect();
        assert_eq!(c.len(), 9, "malformed row {i}: {line:?}");
        let f = |j: usize| -> f64 {
            c[j].trim()
                .parse()
                .unwrap_or_else(|e| panic!("row {i} col {j} ({:?}): {e}", c[j]))
        };
        rows.push(Row {
            idx: c[0].trim().parse().unwrap(),
            time_s: f(1),
            setpoint: f(2),
            measured: f(3),
            output: f(4),
            p_term: f(5),
            i_term: f(6),
            d_term: f(7),
            integral_frozen: c[8].trim() == "1",
        });
    }
    rows
}

fn assert_close(actual: f64, expected: f64, idx: usize, field: &str) {
    let diff = (actual - expected).abs();
    assert!(
        diff <= TOL,
        "row {idx} {field}: rust={actual} ref={expected} (|Δ|={diff:e} > {TOL:e})"
    );
}

#[test]
fn replay_matches_reference_pid() {
    let rows = load_rows();
    assert!(rows.len() >= 200, "fixture too small ({} rows)", rows.len());

    // Same construction as config.example.py defaults.
    let mut pid = Pid::new(25.0, 0.14, 160.0, 0.0, 100.0);

    let mut saturated = 0usize;
    let mut neg_error = 0usize;

    for r in &rows {
        let out = pid.update(r.setpoint, r.measured, r.time_s);
        let s = pid.stats();

        assert_close(out, r.output, r.idx, "output");
        assert_close(s.p_term, r.p_term, r.idx, "p_term");
        assert_close(s.i_term, r.i_term, r.idx, "i_term");
        assert_close(s.d_term, r.d_term, r.idx, "d_term");
        assert_eq!(
            s.integral_frozen, r.integral_frozen,
            "row {} integral_frozen: rust={} ref={}",
            r.idx, s.integral_frozen, r.integral_frozen
        );

        if out >= 100.0 || out <= 0.0 {
            saturated += 1;
        }
        if r.setpoint - r.measured < 0.0 {
            neg_error += 1;
        }
    }

    // Guard the fixture actually exercises the hard paths (not a flat curve).
    assert!(saturated > 50, "fixture barely saturates ({saturated})");
    assert!(neg_error > 20, "fixture lacks negative-error samples ({neg_error})");
}
